// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init.proto

public final class Init {
  private Init() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 luckyValue = 3;</code>
     * @return The luckyValue.
     */
    int getLuckyValue();

    /**
     * <code>int32 moodValue = 4;</code>
     * @return The moodValue.
     */
    int getMoodValue();

    /**
     * <code>int32 money = 5;</code>
     * @return The money.
     */
    int getMoney();

    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    int getEventFinishedDataCount();
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    boolean containsEventFinishedData(
        int key);
    /**
     * Use {@link #getEventFinishedDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getEventFinishedData();
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getEventFinishedDataMap();
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */

    int getEventFinishedDataOrDefault(
        int key,
        int defaultValue);
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */

    int getEventFinishedDataOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code RoleInfo}
   */
  public static final class RoleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoleInfo)
      RoleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoleInfo.newBuilder() to construct.
    private RoleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleInfo() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              luckyValue_ = input.readInt32();
              break;
            }
            case 32: {

              moodValue_ = input.readInt32();
              break;
            }
            case 40: {

              money_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                eventFinishedData_ = com.google.protobuf.MapField.newMapField(
                    EventFinishedDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              eventFinishedData__ = input.readMessage(
                  EventFinishedDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              eventFinishedData_.getMutableMap().put(
                  eventFinishedData__.getKey(), eventFinishedData__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Init.internal_static_RoleInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetEventFinishedData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Init.internal_static_RoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Init.RoleInfo.class, Init.RoleInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LUCKYVALUE_FIELD_NUMBER = 3;
    private int luckyValue_;
    /**
     * <code>int32 luckyValue = 3;</code>
     * @return The luckyValue.
     */
    @java.lang.Override
    public int getLuckyValue() {
      return luckyValue_;
    }

    public static final int MOODVALUE_FIELD_NUMBER = 4;
    private int moodValue_;
    /**
     * <code>int32 moodValue = 4;</code>
     * @return The moodValue.
     */
    @java.lang.Override
    public int getMoodValue() {
      return moodValue_;
    }

    public static final int MONEY_FIELD_NUMBER = 5;
    private int money_;
    /**
     * <code>int32 money = 5;</code>
     * @return The money.
     */
    @java.lang.Override
    public int getMoney() {
      return money_;
    }

    public static final int EVENTFINISHEDDATA_FIELD_NUMBER = 6;
    private static final class EventFinishedDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  Init.internal_static_RoleInfo_EventFinishedDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> eventFinishedData_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetEventFinishedData() {
      if (eventFinishedData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventFinishedDataDefaultEntryHolder.defaultEntry);
      }
      return eventFinishedData_;
    }

    public int getEventFinishedDataCount() {
      return internalGetEventFinishedData().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */

    @java.lang.Override
    public boolean containsEventFinishedData(
        int key) {
      
      return internalGetEventFinishedData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventFinishedDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getEventFinishedData() {
      return getEventFinishedDataMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getEventFinishedDataMap() {
      return internalGetEventFinishedData().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    @java.lang.Override

    public int getEventFinishedDataOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetEventFinishedData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
     */
    @java.lang.Override

    public int getEventFinishedDataOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetEventFinishedData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (luckyValue_ != 0) {
        output.writeInt32(3, luckyValue_);
      }
      if (moodValue_ != 0) {
        output.writeInt32(4, moodValue_);
      }
      if (money_ != 0) {
        output.writeInt32(5, money_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetEventFinishedData(),
          EventFinishedDataDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (luckyValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, luckyValue_);
      }
      if (moodValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, moodValue_);
      }
      if (money_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, money_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetEventFinishedData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        eventFinishedData__ = EventFinishedDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, eventFinishedData__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Init.RoleInfo)) {
        return super.equals(obj);
      }
      Init.RoleInfo other = (Init.RoleInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getLuckyValue()
          != other.getLuckyValue()) return false;
      if (getMoodValue()
          != other.getMoodValue()) return false;
      if (getMoney()
          != other.getMoney()) return false;
      if (!internalGetEventFinishedData().equals(
          other.internalGetEventFinishedData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LUCKYVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getLuckyValue();
      hash = (37 * hash) + MOODVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getMoodValue();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney();
      if (!internalGetEventFinishedData().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTFINISHEDDATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEventFinishedData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Init.RoleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.RoleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.RoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.RoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.RoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.RoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.RoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Init.RoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Init.RoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Init.RoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Init.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Init.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Init.RoleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoleInfo)
        Init.RoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Init.internal_static_RoleInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetEventFinishedData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableEventFinishedData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Init.internal_static_RoleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Init.RoleInfo.class, Init.RoleInfo.Builder.class);
      }

      // Construct using Init.RoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        luckyValue_ = 0;

        moodValue_ = 0;

        money_ = 0;

        internalGetMutableEventFinishedData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Init.internal_static_RoleInfo_descriptor;
      }

      @java.lang.Override
      public Init.RoleInfo getDefaultInstanceForType() {
        return Init.RoleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public Init.RoleInfo build() {
        Init.RoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Init.RoleInfo buildPartial() {
        Init.RoleInfo result = new Init.RoleInfo(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.luckyValue_ = luckyValue_;
        result.moodValue_ = moodValue_;
        result.money_ = money_;
        result.eventFinishedData_ = internalGetEventFinishedData();
        result.eventFinishedData_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Init.RoleInfo) {
          return mergeFrom((Init.RoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Init.RoleInfo other) {
        if (other == Init.RoleInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLuckyValue() != 0) {
          setLuckyValue(other.getLuckyValue());
        }
        if (other.getMoodValue() != 0) {
          setMoodValue(other.getMoodValue());
        }
        if (other.getMoney() != 0) {
          setMoney(other.getMoney());
        }
        internalGetMutableEventFinishedData().mergeFrom(
            other.internalGetEventFinishedData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Init.RoleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Init.RoleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int luckyValue_ ;
      /**
       * <code>int32 luckyValue = 3;</code>
       * @return The luckyValue.
       */
      @java.lang.Override
      public int getLuckyValue() {
        return luckyValue_;
      }
      /**
       * <code>int32 luckyValue = 3;</code>
       * @param value The luckyValue to set.
       * @return This builder for chaining.
       */
      public Builder setLuckyValue(int value) {
        
        luckyValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 luckyValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLuckyValue() {
        
        luckyValue_ = 0;
        onChanged();
        return this;
      }

      private int moodValue_ ;
      /**
       * <code>int32 moodValue = 4;</code>
       * @return The moodValue.
       */
      @java.lang.Override
      public int getMoodValue() {
        return moodValue_;
      }
      /**
       * <code>int32 moodValue = 4;</code>
       * @param value The moodValue to set.
       * @return This builder for chaining.
       */
      public Builder setMoodValue(int value) {
        
        moodValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 moodValue = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoodValue() {
        
        moodValue_ = 0;
        onChanged();
        return this;
      }

      private int money_ ;
      /**
       * <code>int32 money = 5;</code>
       * @return The money.
       */
      @java.lang.Override
      public int getMoney() {
        return money_;
      }
      /**
       * <code>int32 money = 5;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(int value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 money = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        
        money_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> eventFinishedData_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetEventFinishedData() {
        if (eventFinishedData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventFinishedDataDefaultEntryHolder.defaultEntry);
        }
        return eventFinishedData_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetMutableEventFinishedData() {
        onChanged();;
        if (eventFinishedData_ == null) {
          eventFinishedData_ = com.google.protobuf.MapField.newMapField(
              EventFinishedDataDefaultEntryHolder.defaultEntry);
        }
        if (!eventFinishedData_.isMutable()) {
          eventFinishedData_ = eventFinishedData_.copy();
        }
        return eventFinishedData_;
      }

      public int getEventFinishedDataCount() {
        return internalGetEventFinishedData().getMap().size();
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */

      @java.lang.Override
      public boolean containsEventFinishedData(
          int key) {
        
        return internalGetEventFinishedData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventFinishedDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer> getEventFinishedData() {
        return getEventFinishedDataMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, java.lang.Integer> getEventFinishedDataMap() {
        return internalGetEventFinishedData().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */
      @java.lang.Override

      public int getEventFinishedDataOrDefault(
          int key,
          int defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetEventFinishedData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */
      @java.lang.Override

      public int getEventFinishedDataOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetEventFinishedData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEventFinishedData() {
        internalGetMutableEventFinishedData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */

      public Builder removeEventFinishedData(
          int key) {
        
        internalGetMutableEventFinishedData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer>
      getMutableEventFinishedData() {
        return internalGetMutableEventFinishedData().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */
      public Builder putEventFinishedData(
          int key,
          int value) {
        
        
        internalGetMutableEventFinishedData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; eventFinishedData = 6;</code>
       */

      public Builder putAllEventFinishedData(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        internalGetMutableEventFinishedData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoleInfo)
    }

    // @@protoc_insertion_point(class_scope:RoleInfo)
    private static final Init.RoleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Init.RoleInfo();
    }

    public static Init.RoleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleInfo>
        PARSER = new com.google.protobuf.AbstractParser<RoleInfo>() {
      @java.lang.Override
      public RoleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Init.RoleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WeatherInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code WeatherInfo}
   */
  public static final class WeatherInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WeatherInfo)
      WeatherInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WeatherInfo.newBuilder() to construct.
    private WeatherInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeatherInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WeatherInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WeatherInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Init.internal_static_WeatherInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Init.internal_static_WeatherInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Init.WeatherInfo.class, Init.WeatherInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Init.WeatherInfo)) {
        return super.equals(obj);
      }
      Init.WeatherInfo other = (Init.WeatherInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Init.WeatherInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.WeatherInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.WeatherInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.WeatherInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.WeatherInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Init.WeatherInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Init.WeatherInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Init.WeatherInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Init.WeatherInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Init.WeatherInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Init.WeatherInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Init.WeatherInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Init.WeatherInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeatherInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WeatherInfo)
        Init.WeatherInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Init.internal_static_WeatherInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Init.internal_static_WeatherInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Init.WeatherInfo.class, Init.WeatherInfo.Builder.class);
      }

      // Construct using Init.WeatherInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Init.internal_static_WeatherInfo_descriptor;
      }

      @java.lang.Override
      public Init.WeatherInfo getDefaultInstanceForType() {
        return Init.WeatherInfo.getDefaultInstance();
      }

      @java.lang.Override
      public Init.WeatherInfo build() {
        Init.WeatherInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Init.WeatherInfo buildPartial() {
        Init.WeatherInfo result = new Init.WeatherInfo(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Init.WeatherInfo) {
          return mergeFrom((Init.WeatherInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Init.WeatherInfo other) {
        if (other == Init.WeatherInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Init.WeatherInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Init.WeatherInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WeatherInfo)
    }

    // @@protoc_insertion_point(class_scope:WeatherInfo)
    private static final Init.WeatherInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Init.WeatherInfo();
    }

    public static Init.WeatherInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeatherInfo>
        PARSER = new com.google.protobuf.AbstractParser<WeatherInfo>() {
      @java.lang.Override
      public WeatherInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeatherInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WeatherInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Init.WeatherInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleInfo_EventFinishedDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleInfo_EventFinishedDataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeatherInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeatherInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ninit.proto\"\321\001\n\010RoleInfo\022\n\n\002id\030\001 \001(\005\022\014\n" +
      "\004name\030\002 \001(\t\022\022\n\nluckyValue\030\003 \001(\005\022\021\n\tmoodV" +
      "alue\030\004 \001(\005\022\r\n\005money\030\005 \001(\005\022;\n\021eventFinish" +
      "edData\030\006 \003(\0132 .RoleInfo.EventFinishedDat" +
      "aEntry\0328\n\026EventFinishedDataEntry\022\013\n\003key\030" +
      "\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\"\031\n\013WeatherInfo\022" +
      "\n\n\002id\030\001 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RoleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "LuckyValue", "MoodValue", "Money", "EventFinishedData", });
    internal_static_RoleInfo_EventFinishedDataEntry_descriptor =
      internal_static_RoleInfo_descriptor.getNestedTypes().get(0);
    internal_static_RoleInfo_EventFinishedDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleInfo_EventFinishedDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_WeatherInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WeatherInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeatherInfo_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
