// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GameMessage.MsgType msgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.GameMessage.MsgType msgType = 1;</code>
     * @return The msgType.
     */
    Message.GameMessage.MsgType getMsgType();

    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     * @return Whether the c2sInitGame field is set.
     */
    boolean hasC2SInitGame();
    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     * @return The c2sInitGame.
     */
    Message.C2S_initGameMessage getC2SInitGame();
    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     */
    Message.C2S_initGameMessageOrBuilder getC2SInitGameOrBuilder();

    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     * @return Whether the s2cInitGame field is set.
     */
    boolean hasS2CInitGame();
    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     * @return The s2cInitGame.
     */
    Message.S2C_initGameMessage getS2CInitGame();
    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     */
    Message.S2C_initGameMessageOrBuilder getS2CInitGameOrBuilder();

    public Message.GameMessage.MsgBodyCase getMsgBodyCase();
  }
  /**
   * Protobuf type {@code GameMessage}
   */
  public static final class GameMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameMessage)
      GameMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameMessage.newBuilder() to construct.
    private GameMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameMessage() {
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 18: {
              Message.C2S_initGameMessage.Builder subBuilder = null;
              if (msgBodyCase_ == 2) {
                subBuilder = ((Message.C2S_initGameMessage) msgBody_).toBuilder();
              }
              msgBody_ =
                  input.readMessage(Message.C2S_initGameMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Message.C2S_initGameMessage) msgBody_);
                msgBody_ = subBuilder.buildPartial();
              }
              msgBodyCase_ = 2;
              break;
            }
            case 26: {
              Message.S2C_initGameMessage.Builder subBuilder = null;
              if (msgBodyCase_ == 3) {
                subBuilder = ((Message.S2C_initGameMessage) msgBody_).toBuilder();
              }
              msgBody_ =
                  input.readMessage(Message.S2C_initGameMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Message.S2C_initGameMessage) msgBody_);
                msgBody_ = subBuilder.buildPartial();
              }
              msgBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_GameMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_GameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.GameMessage.class, Message.GameMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code GameMessage.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>C2S_initGameMessage = 1;</code>
       */
      C2S_initGameMessage(1),
      /**
       * <code>S2C_initGameMessage = 2;</code>
       */
      S2C_initGameMessage(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>C2S_initGameMessage = 1;</code>
       */
      public static final int C2S_initGameMessage_VALUE = 1;
      /**
       * <code>S2C_initGameMessage = 2;</code>
       */
      public static final int S2C_initGameMessage_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return C2S_initGameMessage;
          case 2: return S2C_initGameMessage;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.GameMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GameMessage.MsgType)
    }

    private int msgBodyCase_ = 0;
    private java.lang.Object msgBody_;
    public enum MsgBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      C2S_INITGAME(2),
      S2C_INITGAME(3),
      MSGBODY_NOT_SET(0);
      private final int value;
      private MsgBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgBodyCase forNumber(int value) {
        switch (value) {
          case 2: return C2S_INITGAME;
          case 3: return S2C_INITGAME;
          case 0: return MSGBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgBodyCase
    getMsgBodyCase() {
      return MsgBodyCase.forNumber(
          msgBodyCase_);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>.GameMessage.MsgType msgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.GameMessage.MsgType msgType = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override public Message.GameMessage.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      Message.GameMessage.MsgType result = Message.GameMessage.MsgType.valueOf(msgType_);
      return result == null ? Message.GameMessage.MsgType.UNRECOGNIZED : result;
    }

    public static final int C2S_INITGAME_FIELD_NUMBER = 2;
    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     * @return Whether the c2sInitGame field is set.
     */
    @java.lang.Override
    public boolean hasC2SInitGame() {
      return msgBodyCase_ == 2;
    }
    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     * @return The c2sInitGame.
     */
    @java.lang.Override
    public Message.C2S_initGameMessage getC2SInitGame() {
      if (msgBodyCase_ == 2) {
         return (Message.C2S_initGameMessage) msgBody_;
      }
      return Message.C2S_initGameMessage.getDefaultInstance();
    }
    /**
     * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
     */
    @java.lang.Override
    public Message.C2S_initGameMessageOrBuilder getC2SInitGameOrBuilder() {
      if (msgBodyCase_ == 2) {
         return (Message.C2S_initGameMessage) msgBody_;
      }
      return Message.C2S_initGameMessage.getDefaultInstance();
    }

    public static final int S2C_INITGAME_FIELD_NUMBER = 3;
    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     * @return Whether the s2cInitGame field is set.
     */
    @java.lang.Override
    public boolean hasS2CInitGame() {
      return msgBodyCase_ == 3;
    }
    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     * @return The s2cInitGame.
     */
    @java.lang.Override
    public Message.S2C_initGameMessage getS2CInitGame() {
      if (msgBodyCase_ == 3) {
         return (Message.S2C_initGameMessage) msgBody_;
      }
      return Message.S2C_initGameMessage.getDefaultInstance();
    }
    /**
     * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
     */
    @java.lang.Override
    public Message.S2C_initGameMessageOrBuilder getS2CInitGameOrBuilder() {
      if (msgBodyCase_ == 3) {
         return (Message.S2C_initGameMessage) msgBody_;
      }
      return Message.S2C_initGameMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != Message.GameMessage.MsgType.UNIVERSAL.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (msgBodyCase_ == 2) {
        output.writeMessage(2, (Message.C2S_initGameMessage) msgBody_);
      }
      if (msgBodyCase_ == 3) {
        output.writeMessage(3, (Message.S2C_initGameMessage) msgBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != Message.GameMessage.MsgType.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (msgBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Message.C2S_initGameMessage) msgBody_);
      }
      if (msgBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Message.S2C_initGameMessage) msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.GameMessage)) {
        return super.equals(obj);
      }
      Message.GameMessage other = (Message.GameMessage) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getMsgBodyCase().equals(other.getMsgBodyCase())) return false;
      switch (msgBodyCase_) {
        case 2:
          if (!getC2SInitGame()
              .equals(other.getC2SInitGame())) return false;
          break;
        case 3:
          if (!getS2CInitGame()
              .equals(other.getS2CInitGame())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      switch (msgBodyCase_) {
        case 2:
          hash = (37 * hash) + C2S_INITGAME_FIELD_NUMBER;
          hash = (53 * hash) + getC2SInitGame().hashCode();
          break;
        case 3:
          hash = (37 * hash) + S2C_INITGAME_FIELD_NUMBER;
          hash = (53 * hash) + getS2CInitGame().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.GameMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.GameMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.GameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.GameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.GameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.GameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.GameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.GameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.GameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.GameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.GameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameMessage)
        Message.GameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_GameMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_GameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.GameMessage.class, Message.GameMessage.Builder.class);
      }

      // Construct using Message.GameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        msgBodyCase_ = 0;
        msgBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_GameMessage_descriptor;
      }

      @java.lang.Override
      public Message.GameMessage getDefaultInstanceForType() {
        return Message.GameMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Message.GameMessage build() {
        Message.GameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Message.GameMessage buildPartial() {
        Message.GameMessage result = new Message.GameMessage(this);
        result.msgType_ = msgType_;
        if (msgBodyCase_ == 2) {
          if (c2SInitGameBuilder_ == null) {
            result.msgBody_ = msgBody_;
          } else {
            result.msgBody_ = c2SInitGameBuilder_.build();
          }
        }
        if (msgBodyCase_ == 3) {
          if (s2CInitGameBuilder_ == null) {
            result.msgBody_ = msgBody_;
          } else {
            result.msgBody_ = s2CInitGameBuilder_.build();
          }
        }
        result.msgBodyCase_ = msgBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.GameMessage) {
          return mergeFrom((Message.GameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.GameMessage other) {
        if (other == Message.GameMessage.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        switch (other.getMsgBodyCase()) {
          case C2S_INITGAME: {
            mergeC2SInitGame(other.getC2SInitGame());
            break;
          }
          case S2C_INITGAME: {
            mergeS2CInitGame(other.getS2CInitGame());
            break;
          }
          case MSGBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.GameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.GameMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgBodyCase_ = 0;
      private java.lang.Object msgBody_;
      public MsgBodyCase
          getMsgBodyCase() {
        return MsgBodyCase.forNumber(
            msgBodyCase_);
      }

      public Builder clearMsgBody() {
        msgBodyCase_ = 0;
        msgBody_ = null;
        onChanged();
        return this;
      }


      private int msgType_ = 0;
      /**
       * <code>.GameMessage.MsgType msgType = 1;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.GameMessage.MsgType msgType = 1;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.GameMessage.MsgType msgType = 1;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public Message.GameMessage.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        Message.GameMessage.MsgType result = Message.GameMessage.MsgType.valueOf(msgType_);
        return result == null ? Message.GameMessage.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.GameMessage.MsgType msgType = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(Message.GameMessage.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.GameMessage.MsgType msgType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Message.C2S_initGameMessage, Message.C2S_initGameMessage.Builder, Message.C2S_initGameMessageOrBuilder> c2SInitGameBuilder_;
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       * @return Whether the c2sInitGame field is set.
       */
      @java.lang.Override
      public boolean hasC2SInitGame() {
        return msgBodyCase_ == 2;
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       * @return The c2sInitGame.
       */
      @java.lang.Override
      public Message.C2S_initGameMessage getC2SInitGame() {
        if (c2SInitGameBuilder_ == null) {
          if (msgBodyCase_ == 2) {
            return (Message.C2S_initGameMessage) msgBody_;
          }
          return Message.C2S_initGameMessage.getDefaultInstance();
        } else {
          if (msgBodyCase_ == 2) {
            return c2SInitGameBuilder_.getMessage();
          }
          return Message.C2S_initGameMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      public Builder setC2SInitGame(Message.C2S_initGameMessage value) {
        if (c2SInitGameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgBody_ = value;
          onChanged();
        } else {
          c2SInitGameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      public Builder setC2SInitGame(
          Message.C2S_initGameMessage.Builder builderForValue) {
        if (c2SInitGameBuilder_ == null) {
          msgBody_ = builderForValue.build();
          onChanged();
        } else {
          c2SInitGameBuilder_.setMessage(builderForValue.build());
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      public Builder mergeC2SInitGame(Message.C2S_initGameMessage value) {
        if (c2SInitGameBuilder_ == null) {
          if (msgBodyCase_ == 2 &&
              msgBody_ != Message.C2S_initGameMessage.getDefaultInstance()) {
            msgBody_ = Message.C2S_initGameMessage.newBuilder((Message.C2S_initGameMessage) msgBody_)
                .mergeFrom(value).buildPartial();
          } else {
            msgBody_ = value;
          }
          onChanged();
        } else {
          if (msgBodyCase_ == 2) {
            c2SInitGameBuilder_.mergeFrom(value);
          }
          c2SInitGameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      public Builder clearC2SInitGame() {
        if (c2SInitGameBuilder_ == null) {
          if (msgBodyCase_ == 2) {
            msgBodyCase_ = 0;
            msgBody_ = null;
            onChanged();
          }
        } else {
          if (msgBodyCase_ == 2) {
            msgBodyCase_ = 0;
            msgBody_ = null;
          }
          c2SInitGameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      public Message.C2S_initGameMessage.Builder getC2SInitGameBuilder() {
        return getC2SInitGameFieldBuilder().getBuilder();
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      @java.lang.Override
      public Message.C2S_initGameMessageOrBuilder getC2SInitGameOrBuilder() {
        if ((msgBodyCase_ == 2) && (c2SInitGameBuilder_ != null)) {
          return c2SInitGameBuilder_.getMessageOrBuilder();
        } else {
          if (msgBodyCase_ == 2) {
            return (Message.C2S_initGameMessage) msgBody_;
          }
          return Message.C2S_initGameMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.C2S_initGameMessage c2s_initGame = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Message.C2S_initGameMessage, Message.C2S_initGameMessage.Builder, Message.C2S_initGameMessageOrBuilder> 
          getC2SInitGameFieldBuilder() {
        if (c2SInitGameBuilder_ == null) {
          if (!(msgBodyCase_ == 2)) {
            msgBody_ = Message.C2S_initGameMessage.getDefaultInstance();
          }
          c2SInitGameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Message.C2S_initGameMessage, Message.C2S_initGameMessage.Builder, Message.C2S_initGameMessageOrBuilder>(
                  (Message.C2S_initGameMessage) msgBody_,
                  getParentForChildren(),
                  isClean());
          msgBody_ = null;
        }
        msgBodyCase_ = 2;
        onChanged();;
        return c2SInitGameBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Message.S2C_initGameMessage, Message.S2C_initGameMessage.Builder, Message.S2C_initGameMessageOrBuilder> s2CInitGameBuilder_;
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       * @return Whether the s2cInitGame field is set.
       */
      @java.lang.Override
      public boolean hasS2CInitGame() {
        return msgBodyCase_ == 3;
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       * @return The s2cInitGame.
       */
      @java.lang.Override
      public Message.S2C_initGameMessage getS2CInitGame() {
        if (s2CInitGameBuilder_ == null) {
          if (msgBodyCase_ == 3) {
            return (Message.S2C_initGameMessage) msgBody_;
          }
          return Message.S2C_initGameMessage.getDefaultInstance();
        } else {
          if (msgBodyCase_ == 3) {
            return s2CInitGameBuilder_.getMessage();
          }
          return Message.S2C_initGameMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      public Builder setS2CInitGame(Message.S2C_initGameMessage value) {
        if (s2CInitGameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgBody_ = value;
          onChanged();
        } else {
          s2CInitGameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      public Builder setS2CInitGame(
          Message.S2C_initGameMessage.Builder builderForValue) {
        if (s2CInitGameBuilder_ == null) {
          msgBody_ = builderForValue.build();
          onChanged();
        } else {
          s2CInitGameBuilder_.setMessage(builderForValue.build());
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      public Builder mergeS2CInitGame(Message.S2C_initGameMessage value) {
        if (s2CInitGameBuilder_ == null) {
          if (msgBodyCase_ == 3 &&
              msgBody_ != Message.S2C_initGameMessage.getDefaultInstance()) {
            msgBody_ = Message.S2C_initGameMessage.newBuilder((Message.S2C_initGameMessage) msgBody_)
                .mergeFrom(value).buildPartial();
          } else {
            msgBody_ = value;
          }
          onChanged();
        } else {
          if (msgBodyCase_ == 3) {
            s2CInitGameBuilder_.mergeFrom(value);
          }
          s2CInitGameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      public Builder clearS2CInitGame() {
        if (s2CInitGameBuilder_ == null) {
          if (msgBodyCase_ == 3) {
            msgBodyCase_ = 0;
            msgBody_ = null;
            onChanged();
          }
        } else {
          if (msgBodyCase_ == 3) {
            msgBodyCase_ = 0;
            msgBody_ = null;
          }
          s2CInitGameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      public Message.S2C_initGameMessage.Builder getS2CInitGameBuilder() {
        return getS2CInitGameFieldBuilder().getBuilder();
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      @java.lang.Override
      public Message.S2C_initGameMessageOrBuilder getS2CInitGameOrBuilder() {
        if ((msgBodyCase_ == 3) && (s2CInitGameBuilder_ != null)) {
          return s2CInitGameBuilder_.getMessageOrBuilder();
        } else {
          if (msgBodyCase_ == 3) {
            return (Message.S2C_initGameMessage) msgBody_;
          }
          return Message.S2C_initGameMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.S2C_initGameMessage s2c_initGame = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Message.S2C_initGameMessage, Message.S2C_initGameMessage.Builder, Message.S2C_initGameMessageOrBuilder> 
          getS2CInitGameFieldBuilder() {
        if (s2CInitGameBuilder_ == null) {
          if (!(msgBodyCase_ == 3)) {
            msgBody_ = Message.S2C_initGameMessage.getDefaultInstance();
          }
          s2CInitGameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Message.S2C_initGameMessage, Message.S2C_initGameMessage.Builder, Message.S2C_initGameMessageOrBuilder>(
                  (Message.S2C_initGameMessage) msgBody_,
                  getParentForChildren(),
                  isClean());
          msgBody_ = null;
        }
        msgBodyCase_ = 3;
        onChanged();;
        return s2CInitGameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameMessage)
    }

    // @@protoc_insertion_point(class_scope:GameMessage)
    private static final Message.GameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.GameMessage();
    }

    public static Message.GameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameMessage>
        PARSER = new com.google.protobuf.AbstractParser<GameMessage>() {
      @java.lang.Override
      public GameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Message.GameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_initGameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_initGameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *携带金钱
     * </pre>
     *
     * <code>int32 money = 1;</code>
     * @return The money.
     */
    int getMoney();
  }
  /**
   * Protobuf type {@code C2S_initGameMessage}
   */
  public static final class C2S_initGameMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2S_initGameMessage)
      C2S_initGameMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_initGameMessage.newBuilder() to construct.
    private C2S_initGameMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_initGameMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_initGameMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_initGameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              money_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_C2S_initGameMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_C2S_initGameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.C2S_initGameMessage.class, Message.C2S_initGameMessage.Builder.class);
    }

    public static final int MONEY_FIELD_NUMBER = 1;
    private int money_;
    /**
     * <pre>
     *携带金钱
     * </pre>
     *
     * <code>int32 money = 1;</code>
     * @return The money.
     */
    @java.lang.Override
    public int getMoney() {
      return money_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (money_ != 0) {
        output.writeInt32(1, money_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (money_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, money_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.C2S_initGameMessage)) {
        return super.equals(obj);
      }
      Message.C2S_initGameMessage other = (Message.C2S_initGameMessage) obj;

      if (getMoney()
          != other.getMoney()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.C2S_initGameMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.C2S_initGameMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.C2S_initGameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.C2S_initGameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.C2S_initGameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.C2S_initGameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.C2S_initGameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.C2S_initGameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.C2S_initGameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.C2S_initGameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.C2S_initGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.C2S_initGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.C2S_initGameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_initGameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_initGameMessage)
        Message.C2S_initGameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_C2S_initGameMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_C2S_initGameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.C2S_initGameMessage.class, Message.C2S_initGameMessage.Builder.class);
      }

      // Construct using Message.C2S_initGameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        money_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_C2S_initGameMessage_descriptor;
      }

      @java.lang.Override
      public Message.C2S_initGameMessage getDefaultInstanceForType() {
        return Message.C2S_initGameMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Message.C2S_initGameMessage build() {
        Message.C2S_initGameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Message.C2S_initGameMessage buildPartial() {
        Message.C2S_initGameMessage result = new Message.C2S_initGameMessage(this);
        result.money_ = money_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.C2S_initGameMessage) {
          return mergeFrom((Message.C2S_initGameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.C2S_initGameMessage other) {
        if (other == Message.C2S_initGameMessage.getDefaultInstance()) return this;
        if (other.getMoney() != 0) {
          setMoney(other.getMoney());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.C2S_initGameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.C2S_initGameMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int money_ ;
      /**
       * <pre>
       *携带金钱
       * </pre>
       *
       * <code>int32 money = 1;</code>
       * @return The money.
       */
      @java.lang.Override
      public int getMoney() {
        return money_;
      }
      /**
       * <pre>
       *携带金钱
       * </pre>
       *
       * <code>int32 money = 1;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(int value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *携带金钱
       * </pre>
       *
       * <code>int32 money = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        
        money_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2S_initGameMessage)
    }

    // @@protoc_insertion_point(class_scope:C2S_initGameMessage)
    private static final Message.C2S_initGameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.C2S_initGameMessage();
    }

    public static Message.C2S_initGameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2S_initGameMessage>
        PARSER = new com.google.protobuf.AbstractParser<C2S_initGameMessage>() {
      @java.lang.Override
      public C2S_initGameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_initGameMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_initGameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_initGameMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Message.C2S_initGameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_initGameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:S2C_initGameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     * @return Whether the role field is set.
     */
    boolean hasRole();
    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     * @return The role.
     */
    Init.RoleInfo getRole();
    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     */
    Init.RoleInfoOrBuilder getRoleOrBuilder();

    /**
     * <code>.WeatherInfo weather = 2;</code>
     * @return Whether the weather field is set.
     */
    boolean hasWeather();
    /**
     * <code>.WeatherInfo weather = 2;</code>
     * @return The weather.
     */
    Init.WeatherInfo getWeather();
    /**
     * <code>.WeatherInfo weather = 2;</code>
     */
    Init.WeatherInfoOrBuilder getWeatherOrBuilder();
  }
  /**
   * Protobuf type {@code S2C_initGameMessage}
   */
  public static final class S2C_initGameMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:S2C_initGameMessage)
      S2C_initGameMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_initGameMessage.newBuilder() to construct.
    private S2C_initGameMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_initGameMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_initGameMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_initGameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Init.RoleInfo.Builder subBuilder = null;
              if (role_ != null) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(Init.RoleInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              Init.WeatherInfo.Builder subBuilder = null;
              if (weather_ != null) {
                subBuilder = weather_.toBuilder();
              }
              weather_ = input.readMessage(Init.WeatherInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(weather_);
                weather_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_S2C_initGameMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_S2C_initGameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.S2C_initGameMessage.class, Message.S2C_initGameMessage.Builder.class);
    }

    public static final int ROLE_FIELD_NUMBER = 1;
    private Init.RoleInfo role_;
    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     * @return Whether the role field is set.
     */
    @java.lang.Override
    public boolean hasRole() {
      return role_ != null;
    }
    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     * @return The role.
     */
    @java.lang.Override
    public Init.RoleInfo getRole() {
      return role_ == null ? Init.RoleInfo.getDefaultInstance() : role_;
    }
    /**
     * <pre>
     *游戏角色信息
     * </pre>
     *
     * <code>.RoleInfo role = 1;</code>
     */
    @java.lang.Override
    public Init.RoleInfoOrBuilder getRoleOrBuilder() {
      return getRole();
    }

    public static final int WEATHER_FIELD_NUMBER = 2;
    private Init.WeatherInfo weather_;
    /**
     * <code>.WeatherInfo weather = 2;</code>
     * @return Whether the weather field is set.
     */
    @java.lang.Override
    public boolean hasWeather() {
      return weather_ != null;
    }
    /**
     * <code>.WeatherInfo weather = 2;</code>
     * @return The weather.
     */
    @java.lang.Override
    public Init.WeatherInfo getWeather() {
      return weather_ == null ? Init.WeatherInfo.getDefaultInstance() : weather_;
    }
    /**
     * <code>.WeatherInfo weather = 2;</code>
     */
    @java.lang.Override
    public Init.WeatherInfoOrBuilder getWeatherOrBuilder() {
      return getWeather();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (role_ != null) {
        output.writeMessage(1, getRole());
      }
      if (weather_ != null) {
        output.writeMessage(2, getWeather());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (role_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRole());
      }
      if (weather_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWeather());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.S2C_initGameMessage)) {
        return super.equals(obj);
      }
      Message.S2C_initGameMessage other = (Message.S2C_initGameMessage) obj;

      if (hasRole() != other.hasRole()) return false;
      if (hasRole()) {
        if (!getRole()
            .equals(other.getRole())) return false;
      }
      if (hasWeather() != other.hasWeather()) return false;
      if (hasWeather()) {
        if (!getWeather()
            .equals(other.getWeather())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      if (hasWeather()) {
        hash = (37 * hash) + WEATHER_FIELD_NUMBER;
        hash = (53 * hash) + getWeather().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.S2C_initGameMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.S2C_initGameMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.S2C_initGameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.S2C_initGameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.S2C_initGameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.S2C_initGameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.S2C_initGameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.S2C_initGameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.S2C_initGameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.S2C_initGameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.S2C_initGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.S2C_initGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.S2C_initGameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_initGameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:S2C_initGameMessage)
        Message.S2C_initGameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_S2C_initGameMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_S2C_initGameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.S2C_initGameMessage.class, Message.S2C_initGameMessage.Builder.class);
      }

      // Construct using Message.S2C_initGameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (roleBuilder_ == null) {
          role_ = null;
        } else {
          role_ = null;
          roleBuilder_ = null;
        }
        if (weatherBuilder_ == null) {
          weather_ = null;
        } else {
          weather_ = null;
          weatherBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_S2C_initGameMessage_descriptor;
      }

      @java.lang.Override
      public Message.S2C_initGameMessage getDefaultInstanceForType() {
        return Message.S2C_initGameMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Message.S2C_initGameMessage build() {
        Message.S2C_initGameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Message.S2C_initGameMessage buildPartial() {
        Message.S2C_initGameMessage result = new Message.S2C_initGameMessage(this);
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        if (weatherBuilder_ == null) {
          result.weather_ = weather_;
        } else {
          result.weather_ = weatherBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.S2C_initGameMessage) {
          return mergeFrom((Message.S2C_initGameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.S2C_initGameMessage other) {
        if (other == Message.S2C_initGameMessage.getDefaultInstance()) return this;
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        if (other.hasWeather()) {
          mergeWeather(other.getWeather());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.S2C_initGameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.S2C_initGameMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Init.RoleInfo role_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Init.RoleInfo, Init.RoleInfo.Builder, Init.RoleInfoOrBuilder> roleBuilder_;
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       * @return Whether the role field is set.
       */
      public boolean hasRole() {
        return roleBuilder_ != null || role_ != null;
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       * @return The role.
       */
      public Init.RoleInfo getRole() {
        if (roleBuilder_ == null) {
          return role_ == null ? Init.RoleInfo.getDefaultInstance() : role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Builder setRole(Init.RoleInfo value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Builder setRole(
          Init.RoleInfo.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Builder mergeRole(Init.RoleInfo value) {
        if (roleBuilder_ == null) {
          if (role_ != null) {
            role_ =
              Init.RoleInfo.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = null;
          onChanged();
        } else {
          role_ = null;
          roleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Init.RoleInfo.Builder getRoleBuilder() {
        
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      public Init.RoleInfoOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_ == null ?
              Init.RoleInfo.getDefaultInstance() : role_;
        }
      }
      /**
       * <pre>
       *游戏角色信息
       * </pre>
       *
       * <code>.RoleInfo role = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Init.RoleInfo, Init.RoleInfo.Builder, Init.RoleInfoOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Init.RoleInfo, Init.RoleInfo.Builder, Init.RoleInfoOrBuilder>(
                  getRole(),
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }

      private Init.WeatherInfo weather_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Init.WeatherInfo, Init.WeatherInfo.Builder, Init.WeatherInfoOrBuilder> weatherBuilder_;
      /**
       * <code>.WeatherInfo weather = 2;</code>
       * @return Whether the weather field is set.
       */
      public boolean hasWeather() {
        return weatherBuilder_ != null || weather_ != null;
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       * @return The weather.
       */
      public Init.WeatherInfo getWeather() {
        if (weatherBuilder_ == null) {
          return weather_ == null ? Init.WeatherInfo.getDefaultInstance() : weather_;
        } else {
          return weatherBuilder_.getMessage();
        }
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Builder setWeather(Init.WeatherInfo value) {
        if (weatherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weather_ = value;
          onChanged();
        } else {
          weatherBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Builder setWeather(
          Init.WeatherInfo.Builder builderForValue) {
        if (weatherBuilder_ == null) {
          weather_ = builderForValue.build();
          onChanged();
        } else {
          weatherBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Builder mergeWeather(Init.WeatherInfo value) {
        if (weatherBuilder_ == null) {
          if (weather_ != null) {
            weather_ =
              Init.WeatherInfo.newBuilder(weather_).mergeFrom(value).buildPartial();
          } else {
            weather_ = value;
          }
          onChanged();
        } else {
          weatherBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Builder clearWeather() {
        if (weatherBuilder_ == null) {
          weather_ = null;
          onChanged();
        } else {
          weather_ = null;
          weatherBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Init.WeatherInfo.Builder getWeatherBuilder() {
        
        onChanged();
        return getWeatherFieldBuilder().getBuilder();
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      public Init.WeatherInfoOrBuilder getWeatherOrBuilder() {
        if (weatherBuilder_ != null) {
          return weatherBuilder_.getMessageOrBuilder();
        } else {
          return weather_ == null ?
              Init.WeatherInfo.getDefaultInstance() : weather_;
        }
      }
      /**
       * <code>.WeatherInfo weather = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Init.WeatherInfo, Init.WeatherInfo.Builder, Init.WeatherInfoOrBuilder> 
          getWeatherFieldBuilder() {
        if (weatherBuilder_ == null) {
          weatherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Init.WeatherInfo, Init.WeatherInfo.Builder, Init.WeatherInfoOrBuilder>(
                  getWeather(),
                  getParentForChildren(),
                  isClean());
          weather_ = null;
        }
        return weatherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:S2C_initGameMessage)
    }

    // @@protoc_insertion_point(class_scope:S2C_initGameMessage)
    private static final Message.S2C_initGameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.S2C_initGameMessage();
    }

    public static Message.S2C_initGameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C_initGameMessage>
        PARSER = new com.google.protobuf.AbstractParser<S2C_initGameMessage>() {
      @java.lang.Override
      public S2C_initGameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_initGameMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_initGameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_initGameMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Message.S2C_initGameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_initGameMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2S_initGameMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_initGameMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_S2C_initGameMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\032\ninit.proto\"\347\001\n\013GameMess" +
      "age\022%\n\007msgType\030\001 \001(\0162\024.GameMessage.MsgTy" +
      "pe\022,\n\014c2s_initGame\030\002 \001(\0132\024.C2S_initGameM" +
      "essageH\000\022,\n\014s2c_initGame\030\003 \001(\0132\024.S2C_ini" +
      "tGameMessageH\000\"J\n\007MsgType\022\r\n\tUNIVERSAL\020\000" +
      "\022\027\n\023C2S_initGameMessage\020\001\022\027\n\023S2C_initGam" +
      "eMessage\020\002B\t\n\007msgBody\"$\n\023C2S_initGameMes" +
      "sage\022\r\n\005money\030\001 \001(\005\"M\n\023S2C_initGameMessa" +
      "ge\022\027\n\004role\030\001 \001(\0132\t.RoleInfo\022\035\n\007weather\030\002" +
      " \001(\0132\014.WeatherInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Init.getDescriptor(),
        });
    internal_static_GameMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameMessage_descriptor,
        new java.lang.String[] { "MsgType", "C2SInitGame", "S2CInitGame", "MsgBody", });
    internal_static_C2S_initGameMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_C2S_initGameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2S_initGameMessage_descriptor,
        new java.lang.String[] { "Money", });
    internal_static_S2C_initGameMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_S2C_initGameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_S2C_initGameMessage_descriptor,
        new java.lang.String[] { "Role", "Weather", });
    Init.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
