package com.example.demo.game.role_test1;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test1.proto

public final class Test1 {
  private Test1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Message.MsgType msgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.Message.MsgType msgType = 1;</code>
     * @return The msgType.
     */
    Test1.Message.MsgType getMsgType();

    /**
     * <code>.Test1Msg test1 = 2;</code>
     * @return Whether the test1 field is set.
     */
    boolean hasTest1();
    /**
     * <code>.Test1Msg test1 = 2;</code>
     * @return The test1.
     */
    Test1.Test1Msg getTest1();
    /**
     * <code>.Test1Msg test1 = 2;</code>
     */
    Test1.Test1MsgOrBuilder getTest1OrBuilder();

    /**
     * <code>.Game game = 3;</code>
     * @return Whether the game field is set.
     */
    boolean hasGame();
    /**
     * <code>.Game game = 3;</code>
     * @return The game.
     */
    Test1.Game getGame();
    /**
     * <code>.Game game = 3;</code>
     */
    Test1.GameOrBuilder getGameOrBuilder();

    public Test1.Message.MsgBodyCase getMsgBodyCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 18: {
              Test1.Test1Msg.Builder subBuilder = null;
              if (msgBodyCase_ == 2) {
                subBuilder = ((Test1.Test1Msg) msgBody_).toBuilder();
              }
              msgBody_ =
                  input.readMessage(Test1.Test1Msg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Test1.Test1Msg) msgBody_);
                msgBody_ = subBuilder.buildPartial();
              }
              msgBodyCase_ = 2;
              break;
            }
            case 26: {
              Test1.Game.Builder subBuilder = null;
              if (msgBodyCase_ == 3) {
                subBuilder = ((Test1.Game) msgBody_).toBuilder();
              }
              msgBody_ =
                  input.readMessage(Test1.Game.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Test1.Game) msgBody_);
                msgBody_ = subBuilder.buildPartial();
              }
              msgBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test1.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test1.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Test1.Message.class, Test1.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code Message.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <pre>
       *对应test1Msg
       * </pre>
       *
       * <code>TEST1 = 1;</code>
       */
      TEST1(1),
      /**
       * <pre>
       *对应game
       * </pre>
       *
       * <code>GAME = 2;</code>
       */
      GAME(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <pre>
       *对应test1Msg
       * </pre>
       *
       * <code>TEST1 = 1;</code>
       */
      public static final int TEST1_VALUE = 1;
      /**
       * <pre>
       *对应game
       * </pre>
       *
       * <code>GAME = 2;</code>
       */
      public static final int GAME_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return TEST1;
          case 2: return GAME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Test1.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.MsgType)
    }

    private int msgBodyCase_ = 0;
    private java.lang.Object msgBody_;
    public enum MsgBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      TEST1(2),
      GAME(3),
      MSGBODY_NOT_SET(0);
      private final int value;
      private MsgBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgBodyCase forNumber(int value) {
        switch (value) {
          case 2: return TEST1;
          case 3: return GAME;
          case 0: return MSGBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgBodyCase
    getMsgBodyCase() {
      return MsgBodyCase.forNumber(
          msgBodyCase_);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>.Message.MsgType msgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.Message.MsgType msgType = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override public Test1.Message.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      Test1.Message.MsgType result = Test1.Message.MsgType.valueOf(msgType_);
      return result == null ? Test1.Message.MsgType.UNRECOGNIZED : result;
    }

    public static final int TEST1_FIELD_NUMBER = 2;
    /**
     * <code>.Test1Msg test1 = 2;</code>
     * @return Whether the test1 field is set.
     */
    @java.lang.Override
    public boolean hasTest1() {
      return msgBodyCase_ == 2;
    }
    /**
     * <code>.Test1Msg test1 = 2;</code>
     * @return The test1.
     */
    @java.lang.Override
    public Test1.Test1Msg getTest1() {
      if (msgBodyCase_ == 2) {
         return (Test1.Test1Msg) msgBody_;
      }
      return Test1.Test1Msg.getDefaultInstance();
    }
    /**
     * <code>.Test1Msg test1 = 2;</code>
     */
    @java.lang.Override
    public Test1.Test1MsgOrBuilder getTest1OrBuilder() {
      if (msgBodyCase_ == 2) {
         return (Test1.Test1Msg) msgBody_;
      }
      return Test1.Test1Msg.getDefaultInstance();
    }

    public static final int GAME_FIELD_NUMBER = 3;
    /**
     * <code>.Game game = 3;</code>
     * @return Whether the game field is set.
     */
    @java.lang.Override
    public boolean hasGame() {
      return msgBodyCase_ == 3;
    }
    /**
     * <code>.Game game = 3;</code>
     * @return The game.
     */
    @java.lang.Override
    public Test1.Game getGame() {
      if (msgBodyCase_ == 3) {
         return (Test1.Game) msgBody_;
      }
      return Test1.Game.getDefaultInstance();
    }
    /**
     * <code>.Game game = 3;</code>
     */
    @java.lang.Override
    public Test1.GameOrBuilder getGameOrBuilder() {
      if (msgBodyCase_ == 3) {
         return (Test1.Game) msgBody_;
      }
      return Test1.Game.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != Test1.Message.MsgType.UNIVERSAL.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (msgBodyCase_ == 2) {
        output.writeMessage(2, (Test1.Test1Msg) msgBody_);
      }
      if (msgBodyCase_ == 3) {
        output.writeMessage(3, (Test1.Game) msgBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != Test1.Message.MsgType.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (msgBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Test1.Test1Msg) msgBody_);
      }
      if (msgBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Test1.Game) msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Test1.Message)) {
        return super.equals(obj);
      }
      Test1.Message other = (Test1.Message) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getMsgBodyCase().equals(other.getMsgBodyCase())) return false;
      switch (msgBodyCase_) {
        case 2:
          if (!getTest1()
              .equals(other.getTest1())) return false;
          break;
        case 3:
          if (!getGame()
              .equals(other.getGame())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      switch (msgBodyCase_) {
        case 2:
          hash = (37 * hash) + TEST1_FIELD_NUMBER;
          hash = (53 * hash) + getTest1().hashCode();
          break;
        case 3:
          hash = (37 * hash) + GAME_FIELD_NUMBER;
          hash = (53 * hash) + getGame().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Test1.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Test1.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Test1.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        Test1.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test1.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test1.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test1.Message.class, Test1.Message.Builder.class);
      }

      // Construct using Test1.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        msgBodyCase_ = 0;
        msgBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test1.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public Test1.Message getDefaultInstanceForType() {
        return Test1.Message.getDefaultInstance();
      }

      @java.lang.Override
      public Test1.Message build() {
        Test1.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Test1.Message buildPartial() {
        Test1.Message result = new Test1.Message(this);
        result.msgType_ = msgType_;
        if (msgBodyCase_ == 2) {
          if (test1Builder_ == null) {
            result.msgBody_ = msgBody_;
          } else {
            result.msgBody_ = test1Builder_.build();
          }
        }
        if (msgBodyCase_ == 3) {
          if (gameBuilder_ == null) {
            result.msgBody_ = msgBody_;
          } else {
            result.msgBody_ = gameBuilder_.build();
          }
        }
        result.msgBodyCase_ = msgBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Test1.Message) {
          return mergeFrom((Test1.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Test1.Message other) {
        if (other == Test1.Message.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        switch (other.getMsgBodyCase()) {
          case TEST1: {
            mergeTest1(other.getTest1());
            break;
          }
          case GAME: {
            mergeGame(other.getGame());
            break;
          }
          case MSGBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Test1.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Test1.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgBodyCase_ = 0;
      private java.lang.Object msgBody_;
      public MsgBodyCase
          getMsgBodyCase() {
        return MsgBodyCase.forNumber(
            msgBodyCase_);
      }

      public Builder clearMsgBody() {
        msgBodyCase_ = 0;
        msgBody_ = null;
        onChanged();
        return this;
      }


      private int msgType_ = 0;
      /**
       * <code>.Message.MsgType msgType = 1;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.Message.MsgType msgType = 1;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Message.MsgType msgType = 1;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public Test1.Message.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        Test1.Message.MsgType result = Test1.Message.MsgType.valueOf(msgType_);
        return result == null ? Test1.Message.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Message.MsgType msgType = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(Test1.Message.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Message.MsgType msgType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Test1.Test1Msg, Test1.Test1Msg.Builder, Test1.Test1MsgOrBuilder> test1Builder_;
      /**
       * <code>.Test1Msg test1 = 2;</code>
       * @return Whether the test1 field is set.
       */
      @java.lang.Override
      public boolean hasTest1() {
        return msgBodyCase_ == 2;
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       * @return The test1.
       */
      @java.lang.Override
      public Test1.Test1Msg getTest1() {
        if (test1Builder_ == null) {
          if (msgBodyCase_ == 2) {
            return (Test1.Test1Msg) msgBody_;
          }
          return Test1.Test1Msg.getDefaultInstance();
        } else {
          if (msgBodyCase_ == 2) {
            return test1Builder_.getMessage();
          }
          return Test1.Test1Msg.getDefaultInstance();
        }
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      public Builder setTest1(Test1.Test1Msg value) {
        if (test1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgBody_ = value;
          onChanged();
        } else {
          test1Builder_.setMessage(value);
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      public Builder setTest1(
          Test1.Test1Msg.Builder builderForValue) {
        if (test1Builder_ == null) {
          msgBody_ = builderForValue.build();
          onChanged();
        } else {
          test1Builder_.setMessage(builderForValue.build());
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      public Builder mergeTest1(Test1.Test1Msg value) {
        if (test1Builder_ == null) {
          if (msgBodyCase_ == 2 &&
              msgBody_ != Test1.Test1Msg.getDefaultInstance()) {
            msgBody_ = Test1.Test1Msg.newBuilder((Test1.Test1Msg) msgBody_)
                .mergeFrom(value).buildPartial();
          } else {
            msgBody_ = value;
          }
          onChanged();
        } else {
          if (msgBodyCase_ == 2) {
            test1Builder_.mergeFrom(value);
          }
          test1Builder_.setMessage(value);
        }
        msgBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      public Builder clearTest1() {
        if (test1Builder_ == null) {
          if (msgBodyCase_ == 2) {
            msgBodyCase_ = 0;
            msgBody_ = null;
            onChanged();
          }
        } else {
          if (msgBodyCase_ == 2) {
            msgBodyCase_ = 0;
            msgBody_ = null;
          }
          test1Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      public Test1.Test1Msg.Builder getTest1Builder() {
        return getTest1FieldBuilder().getBuilder();
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      @java.lang.Override
      public Test1.Test1MsgOrBuilder getTest1OrBuilder() {
        if ((msgBodyCase_ == 2) && (test1Builder_ != null)) {
          return test1Builder_.getMessageOrBuilder();
        } else {
          if (msgBodyCase_ == 2) {
            return (Test1.Test1Msg) msgBody_;
          }
          return Test1.Test1Msg.getDefaultInstance();
        }
      }
      /**
       * <code>.Test1Msg test1 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Test1.Test1Msg, Test1.Test1Msg.Builder, Test1.Test1MsgOrBuilder> 
          getTest1FieldBuilder() {
        if (test1Builder_ == null) {
          if (!(msgBodyCase_ == 2)) {
            msgBody_ = Test1.Test1Msg.getDefaultInstance();
          }
          test1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Test1.Test1Msg, Test1.Test1Msg.Builder, Test1.Test1MsgOrBuilder>(
                  (Test1.Test1Msg) msgBody_,
                  getParentForChildren(),
                  isClean());
          msgBody_ = null;
        }
        msgBodyCase_ = 2;
        onChanged();;
        return test1Builder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Test1.Game, Test1.Game.Builder, Test1.GameOrBuilder> gameBuilder_;
      /**
       * <code>.Game game = 3;</code>
       * @return Whether the game field is set.
       */
      @java.lang.Override
      public boolean hasGame() {
        return msgBodyCase_ == 3;
      }
      /**
       * <code>.Game game = 3;</code>
       * @return The game.
       */
      @java.lang.Override
      public Test1.Game getGame() {
        if (gameBuilder_ == null) {
          if (msgBodyCase_ == 3) {
            return (Test1.Game) msgBody_;
          }
          return Test1.Game.getDefaultInstance();
        } else {
          if (msgBodyCase_ == 3) {
            return gameBuilder_.getMessage();
          }
          return Test1.Game.getDefaultInstance();
        }
      }
      /**
       * <code>.Game game = 3;</code>
       */
      public Builder setGame(Test1.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgBody_ = value;
          onChanged();
        } else {
          gameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Game game = 3;</code>
       */
      public Builder setGame(
          Test1.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          msgBody_ = builderForValue.build();
          onChanged();
        } else {
          gameBuilder_.setMessage(builderForValue.build());
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Game game = 3;</code>
       */
      public Builder mergeGame(Test1.Game value) {
        if (gameBuilder_ == null) {
          if (msgBodyCase_ == 3 &&
              msgBody_ != Test1.Game.getDefaultInstance()) {
            msgBody_ = Test1.Game.newBuilder((Test1.Game) msgBody_)
                .mergeFrom(value).buildPartial();
          } else {
            msgBody_ = value;
          }
          onChanged();
        } else {
          if (msgBodyCase_ == 3) {
            gameBuilder_.mergeFrom(value);
          }
          gameBuilder_.setMessage(value);
        }
        msgBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Game game = 3;</code>
       */
      public Builder clearGame() {
        if (gameBuilder_ == null) {
          if (msgBodyCase_ == 3) {
            msgBodyCase_ = 0;
            msgBody_ = null;
            onChanged();
          }
        } else {
          if (msgBodyCase_ == 3) {
            msgBodyCase_ = 0;
            msgBody_ = null;
          }
          gameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Game game = 3;</code>
       */
      public Test1.Game.Builder getGameBuilder() {
        return getGameFieldBuilder().getBuilder();
      }
      /**
       * <code>.Game game = 3;</code>
       */
      @java.lang.Override
      public Test1.GameOrBuilder getGameOrBuilder() {
        if ((msgBodyCase_ == 3) && (gameBuilder_ != null)) {
          return gameBuilder_.getMessageOrBuilder();
        } else {
          if (msgBodyCase_ == 3) {
            return (Test1.Game) msgBody_;
          }
          return Test1.Game.getDefaultInstance();
        }
      }
      /**
       * <code>.Game game = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Test1.Game, Test1.Game.Builder, Test1.GameOrBuilder> 
          getGameFieldBuilder() {
        if (gameBuilder_ == null) {
          if (!(msgBodyCase_ == 3)) {
            msgBody_ = Test1.Game.getDefaultInstance();
          }
          gameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Test1.Game, Test1.Game.Builder, Test1.GameOrBuilder>(
                  (Test1.Game) msgBody_,
                  getParentForChildren(),
                  isClean());
          msgBody_ = null;
        }
        msgBodyCase_ = 3;
        onChanged();;
        return gameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Test1.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Test1.Message();
    }

    public static Test1.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Test1.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Test1MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test1Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID  
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * 姓名  
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 姓名  
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 年龄  
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * 状态 
     * </pre>
     *
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    int getState();
  }
  /**
   * Protobuf type {@code Test1Msg}
   */
  public static final class Test1Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test1Msg)
      Test1MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test1Msg.newBuilder() to construct.
    private Test1Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test1Msg() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Test1Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test1Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test1.internal_static_Test1Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test1.internal_static_Test1Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Test1.Test1Msg.class, Test1.Test1Msg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * ID  
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名  
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名  
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <pre>
     * 年龄  
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <pre>
     * 状态 
     * </pre>
     *
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Test1.Test1Msg)) {
        return super.equals(obj);
      }
      Test1.Test1Msg other = (Test1.Test1Msg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getState()
          != other.getState()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Test1.Test1Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Test1Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Test1Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Test1Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Test1Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Test1Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Test1Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Test1Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Test1Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Test1.Test1Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Test1Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Test1Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Test1.Test1Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test1Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test1Msg)
        Test1.Test1MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test1.internal_static_Test1Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test1.internal_static_Test1Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test1.Test1Msg.class, Test1.Test1Msg.Builder.class);
      }

      // Construct using Test1.Test1Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test1.internal_static_Test1Msg_descriptor;
      }

      @java.lang.Override
      public Test1.Test1Msg getDefaultInstanceForType() {
        return Test1.Test1Msg.getDefaultInstance();
      }

      @java.lang.Override
      public Test1.Test1Msg build() {
        Test1.Test1Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Test1.Test1Msg buildPartial() {
        Test1.Test1Msg result = new Test1.Test1Msg(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Test1.Test1Msg) {
          return mergeFrom((Test1.Test1Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Test1.Test1Msg other) {
        if (other == Test1.Test1Msg.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Test1.Test1Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Test1.Test1Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * ID  
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * ID  
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID  
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名  
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名  
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名  
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名  
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名  
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 年龄  
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 年龄  
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 年龄  
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>int32 state = 4;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return state_;
      }
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>int32 state = 4;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>int32 state = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Test1Msg)
    }

    // @@protoc_insertion_point(class_scope:Test1Msg)
    private static final Test1.Test1Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Test1.Test1Msg();
    }

    public static Test1.Test1Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test1Msg>
        PARSER = new com.google.protobuf.AbstractParser<Test1Msg>() {
      @java.lang.Override
      public Test1Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test1Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test1Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test1Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Test1.Test1Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Game)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *game
     * </pre>
     *
     * <code>string gamename = 1;</code>
     * @return The gamename.
     */
    java.lang.String getGamename();
    /**
     * <pre>
     *game
     * </pre>
     *
     * <code>string gamename = 1;</code>
     * @return The bytes for gamename.
     */
    com.google.protobuf.ByteString
        getGamenameBytes();

    /**
     * <pre>
     *分数
     * </pre>
     *
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    int getNum();
  }
  /**
   * Protobuf type {@code Game}
   */
  public static final class Game extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Game)
      GameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Game.newBuilder() to construct.
    private Game(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Game() {
      gamename_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Game();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Game(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              gamename_ = s;
              break;
            }
            case 16: {

              num_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test1.internal_static_Game_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test1.internal_static_Game_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Test1.Game.class, Test1.Game.Builder.class);
    }

    public static final int GAMENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object gamename_;
    /**
     * <pre>
     *game
     * </pre>
     *
     * <code>string gamename = 1;</code>
     * @return The gamename.
     */
    @java.lang.Override
    public java.lang.String getGamename() {
      java.lang.Object ref = gamename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gamename_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *game
     * </pre>
     *
     * <code>string gamename = 1;</code>
     * @return The bytes for gamename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGamenameBytes() {
      java.lang.Object ref = gamename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gamename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <pre>
     *分数
     * </pre>
     *
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGamenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gamename_);
      }
      if (num_ != 0) {
        output.writeInt32(2, num_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGamenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gamename_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Test1.Game)) {
        return super.equals(obj);
      }
      Test1.Game other = (Test1.Game) obj;

      if (!getGamename()
          .equals(other.getGamename())) return false;
      if (getNum()
          != other.getNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GAMENAME_FIELD_NUMBER;
      hash = (53 * hash) + getGamename().hashCode();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Test1.Game parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Game parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Game parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Game parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Game parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test1.Game parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test1.Game parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Game parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Game parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Test1.Game parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Test1.Game parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Test1.Game parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Test1.Game prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Game}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Game)
        Test1.GameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test1.internal_static_Game_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test1.internal_static_Game_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test1.Game.class, Test1.Game.Builder.class);
      }

      // Construct using Test1.Game.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        gamename_ = "";

        num_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test1.internal_static_Game_descriptor;
      }

      @java.lang.Override
      public Test1.Game getDefaultInstanceForType() {
        return Test1.Game.getDefaultInstance();
      }

      @java.lang.Override
      public Test1.Game build() {
        Test1.Game result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Test1.Game buildPartial() {
        Test1.Game result = new Test1.Game(this);
        result.gamename_ = gamename_;
        result.num_ = num_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Test1.Game) {
          return mergeFrom((Test1.Game)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Test1.Game other) {
        if (other == Test1.Game.getDefaultInstance()) return this;
        if (!other.getGamename().isEmpty()) {
          gamename_ = other.gamename_;
          onChanged();
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Test1.Game parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Test1.Game) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object gamename_ = "";
      /**
       * <pre>
       *game
       * </pre>
       *
       * <code>string gamename = 1;</code>
       * @return The gamename.
       */
      public java.lang.String getGamename() {
        java.lang.Object ref = gamename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gamename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *game
       * </pre>
       *
       * <code>string gamename = 1;</code>
       * @return The bytes for gamename.
       */
      public com.google.protobuf.ByteString
          getGamenameBytes() {
        java.lang.Object ref = gamename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gamename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *game
       * </pre>
       *
       * <code>string gamename = 1;</code>
       * @param value The gamename to set.
       * @return This builder for chaining.
       */
      public Builder setGamename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gamename_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *game
       * </pre>
       *
       * <code>string gamename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGamename() {
        
        gamename_ = getDefaultInstance().getGamename();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *game
       * </pre>
       *
       * <code>string gamename = 1;</code>
       * @param value The bytes for gamename to set.
       * @return This builder for chaining.
       */
      public Builder setGamenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gamename_ = value;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <pre>
       *分数
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @return The num.
       */
      @java.lang.Override
      public int getNum() {
        return num_;
      }
      /**
       * <pre>
       *分数
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分数
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Game)
    }

    // @@protoc_insertion_point(class_scope:Game)
    private static final Test1.Game DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Test1.Game();
    }

    public static Test1.Game getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Game>
        PARSER = new com.google.protobuf.AbstractParser<Game>() {
      @java.lang.Override
      public Game parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Game(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Game> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Game> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Test1.Game getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test1Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test1Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Game_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013test1.proto\"\231\001\n\007Message\022!\n\007msgType\030\001 \001" +
      "(\0162\020.Message.MsgType\022\032\n\005test1\030\002 \001(\0132\t.Te" +
      "st1MsgH\000\022\025\n\004game\030\003 \001(\0132\005.GameH\000\"-\n\007MsgTy" +
      "pe\022\r\n\tUNIVERSAL\020\000\022\t\n\005TEST1\020\001\022\010\n\004GAME\020\002B\t" +
      "\n\007msgBody\"@\n\010Test1Msg\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\r\n\005state\030\004 \001(\005\"%\n\004G" +
      "ame\022\020\n\010gamename\030\001 \001(\t\022\013\n\003num\030\002 \001(\005b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "MsgType", "Test1", "Game", "MsgBody", });
    internal_static_Test1Msg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Test1Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test1Msg_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "State", });
    internal_static_Game_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Game_descriptor,
        new java.lang.String[] { "Gamename", "Num", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
