server:
  port: 8025

spring:
  datasource:
    username: root
    password: 125125
    url: jdbc:mysql://localhost:3306/message?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
logging:
  level:
    com:
      example:
        mapper: debug