server:
  port: 8025

spring:
  datasource:
    username: root
    password: 125125
    url: jdbc:mysql://localhost:3306/blog_limiun?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: 125125
#    jedis:
#      pool:
#        max-active: 1024
#        max-wait: 5000
#        max-idle: 200
#        min-idle: 0
#    connect-timeout: 10000

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
logging:
  level:
    com:
      example:
        mapper : debug

# # Redis数据库索引（默认为0）
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=127.0.0.1
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.pool.max-idle=8
#  # 连接池中的最小空闲连接
#  spring.redis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.timeout=0